@Webhooks.Api_HostAddress = https://localhost:7118

### Create order

POST {{Webhooks.Api_HostAddress}}/orders
Content-Type: application/json

{
  "customerName":"string",
  "amount":123
}


### Create subscription

POST {{Webhooks.Api_HostAddress}}/webhooks/subscriptions
Content-Type: application/json

{
  "eventType":"order.created",
  "webhookUrl":"https://webhook.site/cad4e4c5-7762-4617-ae67-7852834c97f0"
}