<Project Sdk="Aspire.AppHost.Sdk/13.4.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>b0cc0ac9-6d3d-417a-b2d1-1b6496959f17</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Blogs.Api\Blogs.Api.csproj" />
  </ItemGroup>

</Project>
