services:
  calconnect.api:
    image: ${DOCKER_REGISTRY-}calconnectapi
    container_name: CalConnect.Api
    build:
      context: .
      dockerfile: CalConnect.Api/Dockerfile
    depends_on:
      - calconnect.postgres
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://calconnect.seq:5341/ingest/otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    ports: 
      - 5000:8080
      - 5001:8081
  
  calconnect.postgres:
    image: postgres:latest
    container_name: CalConnect.PostgreSql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calconnect
    volumes:
      - ./.containers/db:/var/lib/postgresql/
    ports:
      - 5432:5432

  calconnect.papercut:
    image: changemakerstudiosus/papercut-smtp:latest
    container_name: CalConnect.Papercut
    ports:
      - 8080:8080
      - 25:2525

  calconnect.seq: 
    image: datalust/seq:latest
    container_name: CalConnect.Seq
    volumes:
      - ./.containers/seq:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=YourStrongPassword123!
    ports:
      - 5341:5341
      - 8081:80