<Project Sdk="Aspire.AppHost.Sdk/13.4.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>21f2ee1b-5a8a-40df-a77b-9063b00fa2b6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.5" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.4.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Webhooks.Api\Webhooks.Api.csproj" />
    <ProjectReference Include="..\Webhooks.Processing\Webhooks.Processing.csproj" />
  </ItemGroup>

</Project>
