<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>96b89e0b-8a94-4c21-bc58-86649b3597c4</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Dapper" Version="2.1.79" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="9.1.2" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="Npgsql" Version="10.0.3" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Messaging.Contracts\Messaging.Contracts.csproj" />
	</ItemGroup>
</Project>
